---
- name: EC2
  hosts: all
  gather_facts: false
  become: yes
  vars:
    ansible_user: ec2-user
  tasks:
    - name: stop Docker service
      service:
        name: docker
        state: stopped
        enabled: false
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache service
      service:
        name: httpd
        state: started
    - name: Restart Apache service
      service:
        name: httpd
        state: restarted
    - name: Copy local directory to remote server
      copy:
        src: "../hello-2048/public_html/"
        dest: "/var/www/html/"
        owner: apache
        group: apache
        mode: 0755
